<a href="https://colab.research.google.com/github/isitoptopi/dheeraj-bhardwaj-ml-102217230/blob/main/1ML_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1: Questions on Basic NumPy Array

In [ ]:
import numpy as np

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [ ]:
arr=np.array([1,2,3,6,4,5])
print(arr)
print(np.flip(arr))

[1 2 3 6 4 5]
[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods


In [ ]:
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
print(array1.flatten())
print(np.ravel(array1))

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
cmp=arr1==arr2
eq_arr=cmp.all()
print(eq_arr)

True


(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [ ]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
x_freq=np.bincount(x).argmax()
y_freq=np.bincount(y).argmax()
print(x)
print(x_freq)
print(np.where(x==x_freq))
print(y)
print(y_freq)
print(np.where(y==y_freq))

[1 2 3 4 5 1 2 1 1 1]
1
(array([0, 5, 7, 8, 9]),)
[1 1 1 2 3 4 2 4 3 3]
1
(array([0, 1, 2]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [ ]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(gfg)
print(np.sum(gfg))
print(np.sum(gfg,axis=0))
print(np.sum(gfg,axis=1))

(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix


In [ ]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
print(n_array)
print(np.sum(np.diagonal(n_array)))
#print(np.trace(n_array))
w,v=np.linalg.eig(n_array)
print('Eigen values:',w)
print('Eigen vector:',v)
print('Inverse :')
print(np.linalg.inv(n_array))
print(np.linalg.det(n_array))

[[55 25 15]
 [30 44  2]
 [11 45 77]]
176
Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vector: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse :
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]


In [ ]:
p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])
print(np.dot(p,q))
print(np.cov(p,q))

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
p=np.array([[1,2],[2,3],[4,5]])
q=np.array([[4,5,1],[6,7,2]])
p_q=np.dot(p,q)
print(p_q)
print(np.cov(p_q))

[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[ 54.33333333  89.16666667 158.83333333]
 [ 89.16666667 146.33333333 260.66666667]
 [158.83333333 260.66666667 464.33333333]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),

find inner, outer and cartesian product?


In [ ]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print(np.inner(x,y))
print(np.outer(x,y))


Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [ ]:
array=np.array([[1,-2,3],[-4,5,-6]])
print(np.absolute(array))
f_array=array.flatten()
print(np.percentile(f_array,25))
print(np.percentile(f_array,50))
print(np.percentile(f_array,75))

[[1 2 3]
 [4 5 6]]
-3.5
-0.5
2.5


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [ ]:
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements


In [ ]:
array=np.array([10,52,62,16,16,54,453])
print(np.sort(array))
print(np.argsort(array))
print(np.sort(array)[:4])
print(np.sort(array)[-5:])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [ ]:
array=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
print(array[array==array.astype(int)])
print(array[array!=array.astype(int)])

[1. 2. 3. 2.]
[1.2 2.2]


Q4:


(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)


In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path):
    # Open the image file
    with Image.open(path) as img:
        # Convert the image to a numpy array
        img_array = np.array(img)

        # Determine the image mode (RGB or grayscale)
        if img_array.ndim == 3:  # RGB image
            mode = 'RGB'
        elif img_array.ndim == 2:  # Grayscale image
            mode = 'Grayscale'
        else:
            raise ValueError("Unsupported image mode or format")

        # Determine the output filename based on image mode
        output_filename = path.rsplit('.', 1)[0] + '_array.txt'

        # Write the image data to a text file
        with open(output_filename, 'w') as f:
            if mode == 'RGB':
                # Format RGB pixel values as tuples
                for row in img_array:
                    row_data = ' '.join(f'({r},{g},{b})' for r, g, b in row)
                    f.write(row_data + '\n')
            elif mode == 'Grayscale':
                # Format grayscale pixel values as single values
                for row in img_array:
                    row_data = ' '.join(str(pixel) for pixel in row)
                    f.write(row_data + '\n')

    print(f"Image data has been written to {output_filename}")

# Example usage
img_to_array('download.jpeg')

Image data has been written to download_array.txt
