<a href="https://colab.research.google.com/github/isitoptopi/dheeraj-bhardwaj-ml-102217230/blob/main/2mL_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Download the dataset (in csv format) from the following link:

https://www.kaggle.com/jahias/microsoft-adventure-works-cycles-customer-data

The Marketing department of Adventure Works Cycles wants to increase sales by targeting specific
customers for a mailing campaign. The company's database contains a list of past customers and a list of
potential new customers. By investigating the attributes of previous bike buyers, the company hopes to
discover patterns that they can then apply to potential customers. They hope to use the discovered patterns
to predict which potential customers are most likely to purchase a bike from Adventure Works Cycles.

In [ ]:
import pandas as pd
from google.colab import files

**Part 1**

Based on Feature Selection, Cleaning, and Preprocessing to Construct an Input from Data
Source

(a) Examine the values of each attribute and Select a set of attributes only that would affect to predict
future bike buyers to create your input for data mining algorithms. Remove all the unnecessary
attributes. (Select features just by analysis).

(b) Create a new Data Frame with the selected attributes only.

(c) Determine a Data value type (Discrete, or Continuous, then Nominal, Ordinal, Interval, Ratio) of
each attribute in your selection to identify preprocessing tasks to create input for your data mining.

In [ ]:
files.upload()

Saving AWCustomers.csv to AWCustomers.csv


{'AWCustomers.csv': b'CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated\r\n21173,NULL,Chad,C,Yuan,NULL,7090 C. Mount Hood,NULL,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0115,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06\r\n13249,NULL,Ryan,NULL,Perry,NULL,3651 Willow Lake Rd,NULL,Shawnee,British Columbia,Canada,V9B 2C3,787-555-0136,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06\r\n29350,NULL,Julia,NULL,Thompson,NULL,1774 Tice Valley Blvd.,NULL,West Covina,California,United States,91791,120-555-0111,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06\r\n13503,NULL,Theodore,NULL,Gomez,NULL,2103 Baldwin Dr,NULL,Liverpool,England,United Kingdom,L4 4HB,1 (11) 500 555-0167,1977-10-18,Partial College,Skilled M

In [ ]:
files.upload()

Saving AWSales.csv to AWSales.csv


{'AWSales.csv': b'CustomerID,BikeBuyer,AvgMonthSpend\r\n21173,1,50.97\r\n13249,1,53.11\r\n29350,1,54.08\r\n13503,1,56.93\r\n22803,1,55.41\r\n22092,1,49.31\r\n11229,0,56.01\r\n24179,1,49.29\r\n12127,1,50.05\r\n19903,0,54.15\r\n25924,0,54.02\r\n23033,0,58.29\r\n20029,1,52.66\r\n22031,0,52.5\r\n23770,0,49.61\r\n23737,1,49.04\r\n17127,1,50.48\r\n28130,1,51\r\n28455,0,58.69\r\n20161,0,52.3\r\n21325,0,50.38\r\n12128,1,53.22\r\n23679,0,51.88\r\n26799,0,49.72\r\n15726,1,48.76\r\n15473,1,52.03\r\n28685,1,49.89\r\n12302,1,51.15\r\n23523,1,53.53\r\n18713,0,50.59\r\n24082,1,49.29\r\n27886,0,49\r\n21711,1,54.71\r\n22366,1,55.64\r\n15010,0,50.55\r\n22296,0,50.16\r\n23237,0,51.02\r\n13832,1,52.17\r\n26026,1,52.31\r\n17813,1,53.13\r\n26369,0,48.89\r\n18824,0,52.46\r\n21064,0,50.21\r\n28532,1,53.97\r\n16183,0,50.85\r\n25700,0,47.53\r\n21746,1,50.48\r\n26560,0,50.57\r\n16988,1,48.1\r\n18562,1,51.99\r\n14996,1,51.43\r\n26741,1,55.52\r\n19490,1,50.76\r\n12720,1,47.68\r\n14050,1,57.1\r\n11926,0,46.25\r\n28

In [ ]:
df=pd.read_csv('AWCustomers.csv')
df.head()

CustomerID Title FirstName MiddleName  LastName Suffix  \
0       21173   NaN      Chad          C      Yuan    NaN   
1       13249   NaN      Ryan        NaN     Perry    NaN   
2       29350   NaN     Julia        NaN  Thompson    NaN   
3       13503   NaN  Theodore        NaN     Gomez    NaN   
4       22803   NaN  Marshall          J      Shan    NaN   

             AddressLine1 AddressLine2         City    StateProvinceName  ...  \
0      7090 C. Mount Hood          NaN   Wollongong      New South Wales  ...   
1     3651 Willow Lake Rd          NaN      Shawnee     British Columbia  ...   
2  1774 Tice Valley Blvd.          NaN  West Covina           California  ...   
3         2103 Baldwin Dr          NaN    Liverpool              England  ...   
4         Am Gallberg 234          NaN        Werne  Nordrhein-Westfalen  ...   

         Education      Occupation Gender MaritalStatus HomeOwnerFlag  \
0        Bachelors        Clerical      M             M             1   
1  Partial College        Clerical      M             M             1   
2        Bachelors        Clerical      F             S             0   
3  Partial College  Skilled Manual      M             M             1   
4  Partial College  Skilled Manual      M             S             1   

  NumberCarsOwned NumberChildrenAtHome TotalChildren  YearlyIncome  \
0               3                    0             1         81916   
1               2                    1             2         81076   
2               3                    0             0         86387   
3               2                    1             2         61481   
4               1                    0             0         51804   

   LastUpdated  
0   2017-03-06  
1   2017-03-06  
2   2017-03-06  
3   2017-03-06  
4   2017-03-06  

[5 rows x 24 columns]

In [ ]:
df2=pd.read_csv('AWSales.csv')
df2.head()

CustomerID  BikeBuyer  AvgMonthSpend
0       21173          1          50.97
1       13249          1          53.11
2       29350          1          54.08
3       13503          1          56.93
4       22803          1          55.41

In [ ]:
df3=pd.merge(df,df2,on='CustomerID',how='inner')
df3.head()

CustomerID Title FirstName MiddleName  LastName Suffix  \
0       21173   NaN      Chad          C      Yuan    NaN   
1       13249   NaN      Ryan        NaN     Perry    NaN   
2       29350   NaN     Julia        NaN  Thompson    NaN   
3       13503   NaN  Theodore        NaN     Gomez    NaN   
4       22803   NaN  Marshall          J      Shan    NaN   

             AddressLine1 AddressLine2         City    StateProvinceName  ...  \
0      7090 C. Mount Hood          NaN   Wollongong      New South Wales  ...   
1     3651 Willow Lake Rd          NaN      Shawnee     British Columbia  ...   
2  1774 Tice Valley Blvd.          NaN  West Covina           California  ...   
3         2103 Baldwin Dr          NaN    Liverpool              England  ...   
4         Am Gallberg 234          NaN        Werne  Nordrhein-Westfalen  ...   

  Gender MaritalStatus HomeOwnerFlag NumberCarsOwned NumberChildrenAtHome  \
0      M             M             1               3                    0   
1      M             M             1               2                    1   
2      F             S             0               3                    0   
3      M             M             1               2                    1   
4      M             S             1               1                    0   

  TotalChildren YearlyIncome LastUpdated  BikeBuyer  AvgMonthSpend  
0             1        81916  2017-03-06          1          50.97  
1             2        81076  2017-03-06          1          53.11  
2             0        86387  2017-03-06          1          54.08  
3             2        61481  2017-03-06          1          56.93  
4             0        51804  2017-03-06          1          55.41  

[5 rows x 26 columns]

In [ ]:
#Feature selection

fin_df=pd.DataFrame()
fin_df['PostalCode']=df3['PostalCode']
fin_df['Age']=2024-(df3['BirthDate'].str.split('-', expand=True)[0].astype(int))
fin_df['YearlyIncome']=df3['YearlyIncome']
fin_df['Occupation']=df3['Occupation']
fin_df['Gender']=df3['Gender']
fin_df['Education']=df3['Education']
fin_df['MaritalStatus']=df3['MaritalStatus']
fin_df['NumberChildrenAtHome']=df3['NumberChildrenAtHome']
fin_df['NumberCarsOwned']=df3['NumberCarsOwned']
fin_df['AvgMonthSpend']=df3['AvgMonthSpend']
fin_df['BikeBuyer']=df3['BikeBuyer']

fin_df.head()

PostalCode  Age  YearlyIncome      Occupation Gender        Education  \
0       2500   37         81916        Clerical      M        Bachelors   
1    V9B 2C3   52         81076        Clerical      M  Partial College   
2      91791   39         86387        Clerical      F        Bachelors   
3     L4 4HB   47         61481  Skilled Manual      M  Partial College   
4      59368   49         51804  Skilled Manual      M  Partial College   

  MaritalStatus  NumberChildrenAtHome  NumberCarsOwned  AvgMonthSpend  \
0             M                     0                3          50.97   
1             M                     1                2          53.11   
2             S                     0                3          54.08   
3             M                     1                2          56.93   
4             S                     0                1          55.41   

   BikeBuyer  
0          1  
1          1  
2          1  
3          1  
4          1

In [ ]:
fin_df.to_csv('BikeBuyer_Data.csv',index=False)

**Part II**


Depending on the data type of each attribute, transform each object from your preprocessed data.
Use all the data rows (~= 18000 rows) with the selected features as input to apply all the tasks below, do
not perform each task on the smaller data set that you got from your random sampling result.

(a) Handling Null values

(b) Normalization

(c) Discretization (Binning) on Continuous attributes or Categorical Attributes with too many different
values

(d) Standardization/Normalization

(e) Binarization (One Hot Encoding)

In [ ]:
dataFrame = pd.read_csv("BikeBuyer_Data.csv")

In [ ]:
#checking for null values

res=dataFrame.isnull().sum()
print(res)

PostalCode              0
Age                     0
YearlyIncome            0
Occupation              0
Gender                  0
Education               0
MaritalStatus           0
NumberChildrenAtHome    0
NumberCarsOwned         0
AvgMonthSpend           0
BikeBuyer               0
dtype: int64


In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler=MinMaxScaler()
dataFrame['YearlyIncome']=scaler.fit_transform(dataFrame['YearlyIncome'].values.reshape(-1,1)).flatten()
dataFrame['AvgMonthSpend']=scaler.fit_transform(dataFrame['AvgMonthSpend'].values.reshape(-1,1)).flatten()
dataFrame['Age']=scaler.fit_transform(dataFrame['Age'].values.reshape(-1,1)).flatten()

In [ ]:
dataFrame.head()

PostalCode       Age  YearlyIncome      Occupation Gender        Education  \
0       2500  0.185714      0.496842        Clerical      M        Bachelors   
1    V9B 2C3  0.400000      0.489453        Clerical      M  Partial College   
2      91791  0.214286      0.536172        Clerical      F        Bachelors   
3     L4 4HB  0.328571      0.317083  Skilled Manual      M  Partial College   
4      59368  0.357143      0.231958  Skilled Manual      M  Partial College   

  MaritalStatus  NumberChildrenAtHome  NumberCarsOwned  AvgMonthSpend  \
0             M                     0                3       0.324210   
1             M                     1                2       0.425201   
2             S                     0                3       0.470977   
3             M                     1                2       0.605474   
4             S                     0                1       0.533742   

   BikeBuyer  
0          1  
1          1  
2          1  
3          1  
4          1

In [ ]:
final_df=pd.get_dummies(dataFrame,columns=['Gender', 'Education', 'MaritalStatus','Occupation','PostalCode'])
final_df.replace({False: 0, True: 1}, inplace=True)
final_df.head()

Age  YearlyIncome  NumberChildrenAtHome  NumberCarsOwned  \
0  0.185714      0.496842                     0                3   
1  0.400000      0.489453                     1                2   
2  0.214286      0.536172                     0                3   
3  0.328571      0.317083                     1                2   
4  0.357143      0.231958                     0                1   

   AvgMonthSpend  BikeBuyer  Gender_F  Gender_M  Education_Bachelors  \
0       0.324210          1         0         1                    1   
1       0.425201          1         0         1                    0   
2       0.470977          1         1         0                    1   
3       0.605474          1         0         1                    0   
4       0.533742          1         0         1                    0   

   Education_Graduate Degree  ...  PostalCode_W1V 5RN  PostalCode_W1X3SE  \
0                          0  ...                   0                  0   
1                          0  ...                   0                  0   
2                          0  ...                   0                  0   
3                          0  ...                   0                  0   
4                          0  ...                   0                  0   

   PostalCode_W1Y 3RA  PostalCode_WA1  PostalCode_WA1 4SY  PostalCode_WA3  \
0                   0               0                   0               0   
1                   0               0                   0               0   
2                   0               0                   0               0   
3                   0               0                   0               0   
4                   0               0                   0               0   

   PostalCode_WA3 7BH  PostalCode_Y024 1GF  PostalCode_Y03 4TN  \
0                   0                    0                   0   
1                   0                    0                   0   
2                   0                    0                   0   
3                   0                    0                   0   
4                   0                    0                   0   

   PostalCode_YO15  
0                0  
1                0  
2                0  
3                0  
4                0  

[5 rows x 343 columns]

In [ ]:
final_df.to_csv('BikeBuyer_Data_final.csv',index=False)

**Part III**

Make sure each attribute is transformed in a same scale for numeric attributes and Binarization for each
nominal attribute, and each discretized numeric attribute to standardization. Make sure to apply a correct
similarity measure for nominal (one hot encoding)/binary attributes and numeric attributes respectively.

(a) Calculate Similarity in Simple Matching, Jaccard Similarity, and Cosine Similarity between two
following objects of your transformed input data.

(b) Calculate Correlation between two features Commute Distance and Yearly Income

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim=cosine_similarity(final_df)
print(cosine_sim)

[[1.         0.77849894 0.8        ... 0.57154761 0.11547005 0.65319726]
 [0.77849894 1.         0.62279916 ... 0.57207755 0.13483997 0.57207755]
 [0.8        0.62279916 1.         ... 0.73484692 0.34641016 0.65319726]
 ...
 [0.57154761 0.57207755 0.73484692 ... 1.         0.28284271 0.6       ]
 [0.11547005 0.13483997 0.34641016 ... 0.28284271 1.         0.14142136]
 [0.65319726 0.57207755 0.65319726 ... 0.6        0.14142136 1.        ]]
